[build]
  command = "npm install && npm run build"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"

[functions]
  node_bundler = "nft" 